version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.docker
    container_name: nginx 
    restart: always
    volumes:
      - g:/var/nginx/nginx.conf:/etc/nginx/nginx.conf
      - g:/var/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      #- 443:443
    links:
      - gogs

  gogs:
    image: gogs/gogs
    container_name: gogs
    hostname: gogs.xl.com
    restart: always
    volumes:
      - g:/var/gogs:/data
