version: '2'

services:
  gogs:
    image: gogs/gogs
    restart: always
    volumes:
      - /var/docker/gogs:/data
    ports:
      - "10022:22"

  slate:
    image: grumpydocker/slate-builder
    restart: always
    volumes:
      - /var/docker/slate/source:/app/source
      - /var/docker/slate/build:/app/build

  mail:
    build: 
      context: .
      dockerfile: mailhog.docker
    volumes:
      - /var/docker/mailhog:/maildir
    command: /MailHog -storage maildir -maildir-path=/maildir
